apiVersion: v1
kind: Service
metadata:
  name: test-nextjs-app
  namespace: default
spec:
  selector:
    app: test-nextjs-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
